---
title: Medical Device Security 101 Conference
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  presentations:
    title: Presentations
    output: false
  speakers:
    title: Speakers
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: speakers
  values:
    credentials_text: ''
    layout: speakers
permalink: pretty
description: 'A cross-disciplinary research initiative on medical device security,
  privacy, safety, and effectiveness

'
twitter_username: ARC_MedSec
github_username: Jonesy
linkedin_username: https://linkedin.com/
conference_dates: January 15 - 17, 2017
conference_location: Lake Buena Vista, FL
